  private PreparedStatement prepareStatement(Connection conn) throws SQLException {
    if (options == null) {
      generateKeys = true;
      return conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
    }

    if (!options.isAutoGeneratedKeys()) {
      generateKeys = false;
      return conn.prepareStatement(sql, Statement.NO_GENERATED_KEYS);
    }

    if (options.getAutoGeneratedKeysIndexes() == null) {
      generateKeys = true;
      return conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
    }

    if (options.getAutoGeneratedKeysIndexes().getValue(0) instanceof String) {
      String[] columnNames = new String[options.getAutoGeneratedKeysIndexes().size()];
      for (int i = 0; i < columnNames.length; i++) {
        columnNames[i] = options.getAutoGeneratedKeysIndexes().getString(i);
      }

      generateKeys = true;
      return conn.prepareStatement(sql, columnNames);
    }

    if (options.getAutoGeneratedKeysIndexes().getValue(0) instanceof Number) {
      int[] columnIndexes = new int[options.getAutoGeneratedKeysIndexes().size()];
      for (int i = 0; i < columnIndexes.length; i++) {
        columnIndexes[i] = options.getAutoGeneratedKeysIndexes().getInteger(i);
      }

      generateKeys = true;
      return conn.prepareStatement(sql, columnIndexes);
    }

    // invalid type
    throw new SQLException("Invalid type for auto generated keys");
  }
